universe:
  index: "SP500"
  start_date: "2012-01-01"
  end_date: "2025-01-01"
  frequency: "D"
fields: ["open", "high", "low", "close", "volume"]
adjustments: {splits: true, dividends: true}
vendor: {source: "local_csv"}  # replace with "polygon", "tiingo", etc.
